module.exports = {
    CHANNEL_TYPES: {
        TEXT: 'GUILD_TEXT',
        CATEGORY: 'GUILD_CATEGORY',
        VOICE: 'GUILD_VOICE',
        DM: 'DM'
    },
    QUEUE_STATES: {
        TENMANS_WAITING: 'WAITING',
        TENMANS_DRAFTING: 'DRAFTING',
        TENMANS_IN_GAME: 'PLAYING',
        TENMANS_STARTING_DRAFT: 'START_DRAFT',
        TENMANS_MAP_PICK: 'MAP_PICK',
        TENMANS_SIDE_PICK: 'SIDE_PICK'
    },
    TENMANS_QUEUE_POOLS: {
        AVAILABLE: 'AVAILABLE',
        TEAM_ONE: 'TEAM_ONE',
        TEAM_TWO: 'TEAM_TWO',
        SPECTATING: 'SPECTATING'
    },
    QUEUE_TYPES: {
        TENMANS: 'TENMAN'
    },
    VALORANT_RANKS: {
        UNRANKED: 'UNRANKED',
        IRON_ONE: 'IRON_ONE',
        IRON_TWO: 'IRON_TWO',
        IRON_THREE: 'IRON_THREE',
        BRONZE_ONE: 'BRONZE_ONE',
        BRONZE_TWO: 'BRONZE_ONE',
        BRONZE_THREE: 'BRONZE_ONE',
        SILVER_ONE: 'SILVER_ONE',
        SILVER_TWO: 'SILVER_TWO',
        SILVER_THREE: 'SILVER_THREE',
        GOLD_ONE: 'GOLD_ONE',
        GOLD_TWO: 'GOLD_TWO',
        GOLD_THREE: 'GOLD_THREE',
        PLATINUM_ONE: 'PLATINUM_ONE',
        PLATINUM_TWO: 'PLATINUM_TWO',
        PLATINUM_THREE: 'PLATINUM_THREE',
        DIAMOND_ONE: 'DIAMOND_ONE',
        DIAMOND_TWO: 'DIAMOND_TWO',
        DIAMOND_THREE: 'DIAMOND_THREE',
        ASCENDANT_ONE: 'ASCENDANT_ONE',
        ASCENDANT_TWO: 'ASCENDANT_TWO',
        ASCENDANT_THREE: 'ASCENDANT_THREE',
        IMMORTAL_ONE: 'IMMORTAL_ONE',
        IMMORTAL_TWO: 'IMMORTAL_TWO',
        IMMORTAL_THREE: 'IMMORTAL_THREE',
        RADIANT: 'RADIANT'
    },
    DISCORD_ROLES: {
        ADMIN: 'ADMIN',
        MOD: 'MOD',
        TENMANS_BLACKLIST: 'QUEUEBAN',
        TENMANS_HOST: 'QUEUEHOST',
        TIER_ONE_SUB: 'TIERONESUB',
        TIER_TWO_SUB: 'TIERTWOSUB',
        TIER_THREE_SUB: 'TIERTHREESUB'
    }
}